package com.yaroslavm87.minesweeper.model

enum class CellStateType {
    HIDDEN,
    HIDDEN_MARKED,
    REVEALED_0,
    REVEALED_1,
    REVEALED_2,
    REVEALED_3,
    REVEALED_4,
    REVEALED_5,
    REVEALED_6,
    REVEALED_7,
    REVEALED_8,
    REVEALED_0_MARKED,
    REVEALED_1_MARKED,
    REVEALED_2_MARKED,
    REVEALED_3_MARKED,
    REVEALED_4_MARKED,
    REVEALED_5_MARKED,
    REVEALED_6_MARKED,
    REVEALED_7_MARKED,
    REVEALED_8_MARKED,
    REVEALED_MINE_NOT_EXPLODED,
    REVEALED_MINE_NOT_EXPLODED_MARKED,
    REVEALED_MINE_EXPLODED
}